seata:
  registry:
    nacos:
      #指定seata服务器在注册中心的名称 默认seata-server
      application: seata-server
      username: nacos
      password: nacos
      #指定seata服务器在注册中心的组名 默认SEATA_GROUP
      group: SEATA-GROUP
      #指定seata服务器所在的注册中心的地址
      server-addr: localhost:8848
  config:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
    type: nacos